In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
toyota_df=pd.read_csv(r"T:\! Active\Data Analytics\_Projects\04 - Financial Analysis of Car Sector\company_data_csv\7203.T Income Statement (Annual) - Discounting Cash Flows.csv")
tsla_df=pd.read_csv(r"T:\! Active\Data Analytics\_Projects\04 - Financial Analysis of Car Sector\company_data_csv\TSLA Income Statement (Annual) - Discounting Cash Flows.csv")
volkswagen_df=pd.read_csv(r"T:\! Active\Data Analytics\_Projects\04 - Financial Analysis of Car Sector\company_data_csv\VOW3.DE Income Statement (Annual) - Discounting Cash Flows.csv")
ford_df=pd.read_csv(r"T:\! Active\Data Analytics\_Projects\04 - Financial Analysis of Car Sector\company_data_csv\F Income Statement (Annual) - Discounting Cash Flows.csv")
gm_df=pd.read_csv(r"T:\! Active\Data Analytics\_Projects\04 - Financial Analysis of Car Sector\company_data_csv\GM Income Statement (Annual) - Discounting Cash Flows.csv")

display(ford_df)

,Period Ending:,LTM \n (Last Twelve Months),2023\n 12-31,2022\n 12-31,2021\n 12-31,2020\n 12-31,2019\n 12-31,2018\n 12-31,2017\n 12-31,2016\n 12-31,...,1994\n 12-31,1993\n 12-31,1992\n 12-31,1991\n 12-31,1990\n 12-31,1989\n 12-31,1988\n 12-31,1987\n 12-31,1986\n 12-31,1985\n 12-31
0,Report Filing:,NaN,2024-02-07,2023-02-03,2022-02-04,2021-02-05,2020-02-05,2019-02-21,2018-02-08,2017-02-09,...,1995-03-16,1994-03-21,1992-12-31,1991-12-31,1990-12-31,1989-12-31,1988-12-31,1987-12-31,1986-12-31,1985-12-31
1,Revenue,"180,348","176,191","158,057","136,341","127,144","155,900","160,338","156,776","151,800",...,"128,439","108,521","100,132","88,286","97,650","96,146","92,446","71,643","62,716","52,774"
2,Cost of Revenue,"163,313","160,031","134,397","114,651","112,752","134,693","136,269","131,332","126,584",...,"103,203","88,364","80,026","70,371","78,004","72,616","68,233","58,495","51,866","44,435"
3,Gross Profit,"17,035","16,160","23,660","21,690","14,392","21,207","24,069","25,444","25,216",...,"25,236","20,157","20,106","17,915","19,646","23,530","24,212","13,148","10,850","8,339"
4,Operating Expenses,"13,136","10,702","11,259","4,312","5,574","11,415","21,394","21,303","21,700",...,"10,041","9,555","12,985","11,931","9,106","9,550","10,765","6,947","6,793","5,609"
5,Research & Development,"8,200","8,200","7,800","7,600","7,100","7,400","8,200","8,000","7,300",...,0,0,0,0,0,0,0,0,0,0
6,"Selling, General and Administrative","10,683","10,702","10,888","11,915","10,193","11,161","11,403","11,527","12,196",...,"5,131","6,491","6,230","6,153","5,921","5,321","8,307","3,780","3,834","3,217"
7,Other Operating Expenses,"-5,747","-8,200","-7,429","-15,203","-11,719","-7,146","1,791","1,776","2,204",...,"4,910","3,064","6,756","5,778","3,185","4,229","2,458","3,167","2,960","2,393"
8,Operating Income,"3,899","5,458","12,401","17,378","8,818","9,792","2,675","4,141","3,516",...,"15,195","10,602","7,121","5,984","10,540","13,980","13,448","6,201","4,057","2,730"
9,Net Interest(Non Operating),"-4,946",249,"1,282","1,803","1,651","1,355","1,429","1,311","1,032",...,-56,0,0,0,0,0,0,0,0,0
10,Interest Income,"1,257","1,567",639,261,452,809,700,464,299,...,665,0,0,0,0,0,0,0,0,0
11,Interest Expense,"6,203","1,318",-643,"-1,542","-1,199",-546,-729,-847,-733,...,721,0,0,0,0,0,0,0,0,0
12,Equity & Other Income/(Expense),"4,617","-1,740","-16,699","-1,401","-11,585","-11,787",241,"2,696","2,248",...,"-6,350","-6,723","-7,328","-8,637","-9,150","-8,033","-5,149","1,150","1,003",888.8
13,Income Before Tax,"3,570","3,967","-3,016","17,780","-1,116",-640,"4,345","8,148","6,796",...,"8,789","3,879",-207.1,"-2,653","1,391","5,947","8,299","7,351","5,059","3,619"
14,Income Tax Expense,-247,-362,-864,-130,160,-724,650,520,"2,189",...,"3,329","1,350",294.7,-395.4,530.4,"2,112","2,999","2,726","1,774","1,103"
15,Income Attributable to Non-Controlling Interest,-19,-18,0,-27,0,0,18,26,11,...,152,0,"6,883",0,0,0,0,0,0,0
16,Net Income,"3,836","4,347","-2,152","17,937","-1,276",84,"3,677","7,602","4,596",...,"5,308","2,529","-7,385","-2,258",860.1,"3,835","5,300","4,625","3,285","2,515"
17,Depreciation and Amortization,"6,325","6,523","6,493","5,960","7,457","8,490","8,308","8,453","8,717",...,"9,336","3,064","6,756","5,778","3,185","4,229","2,458","3,167","2,960","2,393"
18,EBITDA,"10,224","11,981","18,894","23,338","16,275","18,282","10,983","12,594","12,233",...,"24,531","13,666","13,877","11,762","13,725","18,209","15,905","9,369","7,016","5,123"
19,Earnings Per Share (EPS),0.963,1.09,-0.54,4.49,-0.32,0.021,0.93,1.91,1.16,...,3.16,1.44,-4.84,-2.37,0.94,4.11,5.48,4.52,3.03,2.29
20,Diluted Earnings Per Share,0.954,1.08,-0.54,4.45,-0.32,0.021,0.92,1.9,1.15,...,2.83,1.34,-4.84,-2.37,0.92,4.06,5.41,4.45,3.03,2.22
21,Weighted Average Shares Outstanding,"3,985","3,998","4,014","3,991","3,973","3,972","3,954","3,980","3,973",...,"1,587","1,549","1,527",954,915,933.1,967.2,"1,023","1,084","1,098"
22,Diluted Weighted Average Shares Outstanding,"4,022","4,041","4,014","4,034","3,973","4,004","3,997","4,001","3,999",...,"1,587","1,549","1,527",954,934.9,944.6,979.7,"1,039","1,084","1,133"

In [12]:
def clean_and_transpose(df, company_name):
    # Eliminamos columna LTM:
    df_cleaned = df.drop(columns=df.columns[1])
    
    # Usamos la primera fila como nombres de columnas
    df_cleaned.columns = df_cleaned.iloc[0]
    df_cleaned = df_cleaned.drop(0).reset_index(drop=True)
    
    # Transponer el Dataframe para tener los años como registros
    df_transposed = df_cleaned.set_index(df_cleaned.columns[0]).T
    df_transposed.index.name = 'Year'
    
    # Extraer solo el año de la fecha y convertirlo a entero
    df_transposed.index = pd.to_datetime(df_transposed.index.str.split('\n').str[0]).year

        # Función para limpiar y convertir valores
    def clean_and_convert(x):
        if isinstance(x, str):
            # Eliminar caracteres no numéricos excepto el punto decimal
            x = ''.join(c for c in x if c.isdigit() or c == '.'  or c == '-')
            try:
                return float(x) * 1_000_000
            except ValueError:
                return np.nan
        elif pd.isna(x):
            return np.nan
        else:
            return float(x) * 1_000_000
    
    # Aplicar la función de limpieza y conversión a todas las columnas numéricas
    for col in df_transposed.columns:
        df_transposed[col] = df_transposed[col].apply(clean_and_convert)
    

    # Añadimos nombre de compañía y lo movemos a la primera posición
    df_transposed.insert(0, "company", company_name)
    
    df_transposed = df_transposed.reset_index(drop=False)
    
    return df_transposed

In [20]:
tsla_clean = clean_and_transpose(tsla_df, 'TSLA')
toyota_clean = clean_and_transpose(toyota_df, '7203.T')
volkswagen_clean = clean_and_transpose(volkswagen_df, 'VOW3.DE')
ford_clean = clean_and_transpose(ford_df, 'F')
gm_clean = clean_and_transpose(gm_df, 'GM')

pd.set_option('display.float_format', lambda x: '%.2f' % x)
display(toyota_clean)

Report Filing:,Year,company,Revenue,Cost of Revenue,Gross Profit,Operating Expenses,Research & Development,"Selling, General and Administrative",Other Operating Expenses,Operating Income,...,Income Before Tax,Income Tax Expense,Income Attributable to Non-Controlling Interest,Net Income,Depreciation and Amortization,EBITDA,Earnings Per Share (EPS),Diluted Earnings Per Share,Weighted Average Shares Outstanding,Diluted Weighted Average Shares Outstanding
0,2024,7203.T,45095325000000.00,35727007000000.00,9368318000000.00,4015383000000.00,1202373000000.00,2813010000000.00,0.00,5352935000000.00,...,6201948000000.00,1893665000000.00,-636650000000.00,4944933000000.00,2087066000000.00,7440001000000.00,365900000.00,365900000.00,13513000000.00,13513000000.00
1,2023,7203.T,37154298000000.00,30841282000000.00,6313016000000.00,2643686000000.00,1241686000000.00,3587990000000.00,-2185990000000.00,3669330000000.00,...,3668733000000.00,1175765000000.00,41650000000.00,2451318000000.00,2039904000000.00,5709234000000.00,179500000.00,179500000.00,13658000000.00,13658000000.00
2,2022,7203.T,31379507000000.00,25407834000000.00,5971673000000.00,2975976000000.00,1124262000000.00,2975977000000.00,-1124263000000.00,2995697000000.00,...,3990532000000.00,1115918000000.00,24504000000.00,2850110000000.00,1821880000000.00,4817577000000.00,205200000.00,205200000.00,13887000000.00,13888000000.00
3,2021,7203.T,27214593000000.00,22382220000000.00,4832373000000.00,1867624000000.00,1090424000000.00,2634625000000.00,-1857425000000.00,2964749000000.00,...,2932354000000.00,649976000000.00,37117000000.00,2245261000000.00,1644290000000.00,4609039000000.00,160700000.00,158900000.00,13976000000.00,14206000000.00
4,2020,7203.T,29929992000000.00,24522364000000.00,5407628000000.00,2964759000000.00,1110369000000.00,2964759000000.00,-1110369000000.00,2442869000000.00,...,2554607000000.00,683430000000.00,-164963000000.00,2036140000000.00,1595347000000.00,4038216000000.00,145500000.00,144000000.00,13995000000.00,14230000000.00
5,2019,7203.T,30225681000000.00,24781785000000.00,5443896000000.00,2976351000000.00,1048882000000.00,2976351000000.00,-1048882000000.00,2467545000000.00,...,2285465000000.00,659944000000.00,-257352000000.00,1882873000000.00,1792375000000.00,4259920000000.00,131100000.00,129000000.00,14358000000.00,14593000000.00
6,2018,7203.T,29379510000000.00,23889153000000.00,5490357000000.00,3090495000000.00,1064269000000.00,3090495000000.00,-1064269000000.00,2399862000000.00,...,2620429000000.00,504406000000.00,-377960000000.00,2493983000000.00,1734033000000.00,4133895000000.00,169200000.00,166600000.00,14737000000.00,14974000000.00
7,2017,7203.T,27597193000000.00,22734336000000.00,4862857000000.00,2868485000000.00,1037528000000.00,2868485000000.00,-1037528000000.00,1994372000000.00,...,2193825000000.00,628900000000.00,-266184000000.00,1831109000000.00,1610950000000.00,3605322000000.00,121100000.00,119800000.00,15040000000.00,15279000000.00
8,2016,7203.T,28403118000000.00,22605465000000.00,5797653000000.00,2943682000000.00,1055672000000.00,2943682000000.00,-1055672000000.00,2853971000000.00,...,2983381000000.00,878269000000.00,-207582000000.00,2312694000000.00,1625837000000.00,4479808000000.00,148300000.00,147100000.00,15557000000.00,15725000000.00
9,2015,7203.T,27234521000000.00,21841676000000.00,5392845000000.00,2642281000000.00,1004547000000.00,2642281000000.00,-1004547000000.00,2750564000000.00,...,2892828000000.00,893469000000.00,-173979000000.00,2173338000000.00,1409075000000.00,4159639000000.00,137600000.00,137500000.00,15794000000.00,15802000000.00
10,2014,7203.T,25691911000000.00,20801139000000.00,4890772000000.00,2598660000000.00,910517000000.00,2598660000000.00,-910517000000.00,2292112000000.00,...,2441080000000.00,767808000000.00,-149847000000.00,1823119000000.00,1250853000000.00,3542965000000.00,115100000.00,115000000.00,15845000000.00,15855000000.00
11,2013,7203.T,22064192000000.00,18640995000000.00,3423197000000.00,2102309000000.00,807454000000.00,2102309000000.00,-807454000000.00,1320888000000.00,...,1403649000000.00,551686000000.00,-110200000000.00,962163000000.00,1105109000000.00,2425997000000.00,60760000.00,60760000.00,15835000000.00,15837000000.00
12,2012,7203.T,18583653000000.00,16388564000000.00,2195089000000.00,1839462000000.00,0.00,1839462000000.00,0.00,355627000000.00,...,432873000000.00,262272000000.00,-112958000000.00,283559000000.00,1067830000000.00,1423457000000.00,18040000.00,18040000.00,15717000000.00,15718000000.00
13,2011,7203.T,18993688000000.00,16615326000000.00,2378362000000.00,1910083000000.00,0.00,1910083000000.00,0.00,468279000000.00,...,563290000000.00,312821000000.00,-157714000000.00,408183000000.00,1175573000000.00,1643852000000.00,26030000.00,26030000.00,15679000000.00,15680000000.00
14,2010,7203.T,18950973000000.00,16683797000000.00,2267176000000.00,2119660000000.00,0.00,2119660000000.00,0.00,147516000000.00,...,291468000000.00,92664000000.00,-10652000000.00,209456000000.00,1414569000000.00,1562085000000.00,13360000.00,13360000.00,15680000000.00,15680000000.00
15,2009,7203.T,20529570000000.00,18455800000000.00,2073770000000.00,2534781000000.00,0.00,2534781000000.00,0.00,-461011000000.00,...,-560381000000.00,-56442000000.00,-67002000000.00,-436937000000.00,1495170000000.00,1034159000000.00,-27830000.00,-27830000.00,15701000000.00,15701000000.00
16,2008,7203.T,26163526000000.00,21417390000000.00,4746136000000.00,2486589000000.00,0.00,2486589000000.00,0.00,2259547000000.00,...,2425566000000.00,907169000000.00,-191245000000.00,1709642000000.00,1483996000000.00,3743544000000.00,108100000.00,108100000.00,15887000000.00,15893000000.00
17,2007,7203.T,23901501000000.00,19190927000000.00,4710574000000.00,2476230000000.00,0.00,2476230000000.00,0.00,2234345000000.00,...,2377850000000.00,896495000000.00,-159529000000.00,1640884000000.00,1379912000000.00,3614256000000.00,102200000.00,102100000.00,16052000000.00,16061000000.00
18,2006,7203.T,21078508000000.00,16978461000000.00,4100047000000.00,2217985000000.00,0.00,2217985000000.00,0.00,1882062000000.00,...,2091455000000.00,796728000000.00,-80155000000.00,1374882000000.00,1213630000000.00,3095692000000.00,84150000.00,84120000.00,16267000000.00,16273000000.00
19,2005,7203.T,18524369000000.00,14848427000000.00,3675942000000.00,2006220000000.00,0.00,2006220000000.00,0.00,1669723000000.00,...,1752078000000.00,656909000000.00,-74420000000.00,1169589000000.00,996301000000.00,2666023000000.00,71250000.00,71240000.00,16480000000.00,16484000000.00
20,2004,7203.T,17059738000000.00,13682027000000.00,3377711000000.00,1733424000000.00,0.00,1733424000000.00,0.00,1644287000000.00,...,1741764000000.00,672018000000.00,-76522000000.00,1146268000000.00,956735000000.00,2601022000000.00,68720000.00,68720000.00,16945000000.00,16947000000.00
21,2003,7203.T,15214416000000.00,12109597000000.00,3104819000000.00,1856781000000.00,0.00,1856781000000.00,0.00,1248039000000.00,...,1244382000000.00,507403000000.00,0.00,736979000000.00,854480000000.00,2102519000000.00,42050000.00,42050000.00,17768000000.00,17768000000.00
22,2002,7203.T,14280227000000.00,11304642000000.00,2975584000000.00,1884794000000.00,0.00,1884794000000.00,0.00,1090791000000.00,...,976887000000.00,421723000000.00,0.00,555164000000.00,807826000000.00,1898616000000.00,30540000.00,30540000.00,18277000000.00,18277000000.00
23,2001,7203.T,13371419000000.00,10835856000000.00,2535563000000.00,1730730000000.00,0.00,1730730000000.00,0.00,804833000000.00,...,1220112000000.00,533192000000.00,0.00,686920000000.00,798779000000.00,1603612000000.00,36360000.00,36360000.00,18679000000.00,18680000000.00
24,2000,7203.T,12295109000000.00,8925092000000.00,3370016000000.00,2693794000000.00,0.00,1897760000000.00,796034000000.00,676223000000.00,...,875668000000.00,409166000000.00,0.00,466502000000.00,796034000000.00,1472256000000.00,24870000.00,24870000.00,18747000000.00,18747000000.00
25,1999,7203.T,12603549000000.00,9094677000000.00,3508872000000.00,2767536000000.00,0.00,1913779000000.00,853757000000.00,741336000000.00,...,866976000000.00,420745000000.00,0.00,446231000000.00,853757000000.00,1595093000000.00,23580000.00,23580000.00,18902000000.00,18902000000.00
26,1998,7203.T,11774836000000.00,8597205000000.00,3177631000000.00,2427802000000.00,0.00,1776087000000.00,651715000000.00,749829000000.00,...,815483000000.00,357387000000.00,0.00,458096000000.00,651715000000.00,1401545000000.00,23960000.00,23960000.00,18230000000.00,18230000000.00
27,1997,7203.T,12222187000000.00,9300218000000.00,2921969000000.00,2258256000000.00,0.00,1650022000000.00,608234000000.00,663712000000.00,...,738724000000.00,353493000000.00,0.00,385230000000.00,608234000000.00,1271946000000.00,20050000.00,20050000.00,19211000000.00,19211000000.00
28,1996,7203.T,10829983000000.00,8553227000000.00,2276755000000.00,1925081000000.00,0.00,1369703000000.00,555378000000.00,351674000000.00,...,445076000000.00,185433000000.00,0.00,259643000000.00,555378000000.00,907052000000.00,13280000.00,13280000.00,19551000000.00,19551000000.00
29,1995,7203.T,8279478000000.00,6674247000000.00,1605231000000.00,1344519000000.00,0.00,1007750000000.00,336769000000.00,260711000000.00,...,296412000000.00,161887000000.00,0.00,134525000000.00,336769000000.00,597481000000.00,7000000.00,7000000.00,19222000000.00,19222000000.00
30,1994,7203.T,9354895000000.00,7685465000000.00,1669430000000.00,1533317000000.00,0.00,1073702000000.00,459615000000.00,136113000000.00,...,249436000000.00,123729000000.00,0.00,125708000000.00,459615000000.00,595728000000.00,6690000.00,6690000.00,18779000000.00,18779000000.00
31,1994,7203.T,10172512000000.00,8430469000000.00,1742043000000.00,1560824000000.00,0.00,1078531000000.00,482293000000.00,181219000000.00,...,336637000000.00,160828000000.00,0.00,175809000000.00,482293000000.00,663512000000.00,9180000.00,9180000.00,19159000000.00,19159000000.00
32,1993,7203.T,10165805000000.00,8301494000000.00,1864312000000.00,1645759000000.00,0.00,1173630000000.00,472129000000.00,218553000000.00,...,450491000000.00,212590000000.00,0.00,237901000000.00,472129000000.00,690682000000.00,12330000.00,12330000.00,19297000000.00,19297000000.00
33,1992,7203.T,9869664000000.00,7855203000000.00,2014460000000.00,1513875000000.00,0.00,1129978000000.00,383896000000.00,500586000000.00,...,733537000000.00,301449000000.00,0.00,432089000000.00,383896000000.00,884482000000.00,22330000.00,22330000.00,19349000000.00,19349000000.00
34,1991,7203.T,9202213000000.00,7146919000000.00,2055294000000.00,1411640000000.00,0.00,1071884000000.00,339756000000.00,643654000000.00,...,857389000000.00,415643000000.00,0.00,441745000000.00,339756000000.00,983410000000.00,25110000.00,25110000.00,17590000000.00,17590000000.00
35,1989,7203.T,8037326000000.00,6422894000000.00,1614432000000.00,1145547000000.00,0.00,849904000000.00,295643000000.00,468885000000.00,...,645050000000.00,298090000000.00,0.00,346961000000.00,295643000000.00,764528000000.00,20010000.00,20010000.00,17340000000.00,17340000000.00

In [21]:
# Suponiendo que estas son las tasas de conversión:
eur_to_usd = 1.11  # Ejemplo de tasa de EUR a USD
jpy_to_usd = 0.007  # Ejemplo de tasa de JPY a USD

# Para el DataFrame de EUR:
for col in volkswagen_clean.columns[1:]:
    # Verificamos si la columna es numérica
    if pd.api.types.is_numeric_dtype(volkswagen_clean[col]):
        # Convertir los valores de EUR a USD
        volkswagen_clean[col] = volkswagen_clean[col] * eur_to_usd

# Para el DataFrame de JPY:
for col in toyota_clean.columns[1:]:
    if pd.api.types.is_numeric_dtype(toyota_clean[col]):
        toyota_clean[col] = toyota_clean[col] * jpy_to_usd
display(toyota_clean)

Report Filing:,Year,company,Revenue,Cost of Revenue,Gross Profit,Operating Expenses,Research & Development,"Selling, General and Administrative",Other Operating Expenses,Operating Income,...,Income Before Tax,Income Tax Expense,Income Attributable to Non-Controlling Interest,Net Income,Depreciation and Amortization,EBITDA,Earnings Per Share (EPS),Diluted Earnings Per Share,Weighted Average Shares Outstanding,Diluted Weighted Average Shares Outstanding
0,2024,7203.T,315667275000.00,250089049000.00,65578226000.00,28107681000.00,8416611000.00,19691070000.00,0.00,37470545000.00,...,43413636000.00,13255655000.00,-4456550000.00,34614531000.00,14609462000.00,52080007000.00,2561300.00,2561300.00,94591000.00,94591000.00
1,2023,7203.T,260080086000.00,215888974000.00,44191112000.00,18505802000.00,8691802000.00,25115930000.00,-15301930000.00,25685310000.00,...,25681131000.00,8230355000.00,291550000.00,17159226000.00,14279328000.00,39964638000.00,1256500.00,1256500.00,95606000.00,95606000.00
2,2022,7203.T,219656549000.00,177854838000.00,41801711000.00,20831832000.00,7869834000.00,20831839000.00,-7869841000.00,20969879000.00,...,27933724000.00,7811426000.00,171528000.00,19950770000.00,12753160000.00,33723039000.00,1436400.00,1436400.00,97209000.00,97216000.00
3,2021,7203.T,190502151000.00,156675540000.00,33826611000.00,13073368000.00,7632968000.00,18442375000.00,-13001975000.00,20753243000.00,...,20526478000.00,4549832000.00,259819000.00,15716827000.00,11510030000.00,32263273000.00,1124900.00,1112300.00,97832000.00,99442000.00
4,2020,7203.T,209509944000.00,171656548000.00,37853396000.00,20753313000.00,7772583000.00,20753313000.00,-7772583000.00,17100083000.00,...,17882249000.00,4784010000.00,-1154741000.00,14252980000.00,11167429000.00,28267512000.00,1018500.00,1008000.00,97965000.00,99610000.00
5,2019,7203.T,211579767000.00,173472495000.00,38107272000.00,20834457000.00,7342174000.00,20834457000.00,-7342174000.00,17272815000.00,...,15998255000.00,4619608000.00,-1801464000.00,13180111000.00,12546625000.00,29819440000.00,917700.00,903000.00,100506000.00,102151000.00
6,2018,7203.T,205656570000.00,167224071000.00,38432499000.00,21633465000.00,7449883000.00,21633465000.00,-7449883000.00,16799034000.00,...,18343003000.00,3530842000.00,-2645720000.00,17457881000.00,12138231000.00,28937265000.00,1184400.00,1166200.00,103159000.00,104818000.00
7,2017,7203.T,193180351000.00,159140352000.00,34039999000.00,20079395000.00,7262696000.00,20079395000.00,-7262696000.00,13960604000.00,...,15356775000.00,4402300000.00,-1863288000.00,12817763000.00,11276650000.00,25237254000.00,847700.00,838600.00,105280000.00,106953000.00
8,2016,7203.T,198821826000.00,158238255000.00,40583571000.00,20605774000.00,7389704000.00,20605774000.00,-7389704000.00,19977797000.00,...,20883667000.00,6147883000.00,-1453074000.00,16188858000.00,11380859000.00,31358656000.00,1038100.00,1029700.00,108899000.00,110075000.00
9,2015,7203.T,190641647000.00,152891732000.00,37749915000.00,18495967000.00,7031829000.00,18495967000.00,-7031829000.00,19253948000.00,...,20249796000.00,6254283000.00,-1217853000.00,15213366000.00,9863525000.00,29117473000.00,963200.00,962500.00,110558000.00,110614000.00
10,2014,7203.T,179843377000.00,145607973000.00,34235404000.00,18190620000.00,6373619000.00,18190620000.00,-6373619000.00,16044784000.00,...,17087560000.00,5374656000.00,-1048929000.00,12761833000.00,8755971000.00,24800755000.00,805700.00,805000.00,110915000.00,110985000.00
11,2013,7203.T,154449344000.00,130486965000.00,23962379000.00,14716163000.00,5652178000.00,14716163000.00,-5652178000.00,9246216000.00,...,9825543000.00,3861802000.00,-771400000.00,6735141000.00,7735763000.00,16981979000.00,425320.00,425320.00,110845000.00,110859000.00
12,2012,7203.T,130085571000.00,114719948000.00,15365623000.00,12876234000.00,0.00,12876234000.00,0.00,2489389000.00,...,3030111000.00,1835904000.00,-790706000.00,1984913000.00,7474810000.00,9964199000.00,126280.00,126280.00,110019000.00,110026000.00
13,2011,7203.T,132955816000.00,116307282000.00,16648534000.00,13370581000.00,0.00,13370581000.00,0.00,3277953000.00,...,3943030000.00,2189747000.00,-1103998000.00,2857281000.00,8229011000.00,11506964000.00,182210.00,182210.00,109753000.00,109760000.00
14,2010,7203.T,132656811000.00,116786579000.00,15870232000.00,14837620000.00,0.00,14837620000.00,0.00,1032612000.00,...,2040276000.00,648648000.00,-74564000.00,1466192000.00,9901983000.00,10934595000.00,93520.00,93520.00,109760000.00,109760000.00
15,2009,7203.T,143706990000.00,129190600000.00,14516390000.00,17743467000.00,0.00,17743467000.00,0.00,-3227077000.00,...,-3922667000.00,-395094000.00,-469014000.00,-3058559000.00,10466190000.00,7239113000.00,-194810.00,-194810.00,109907000.00,109907000.00
16,2008,7203.T,183144682000.00,149921730000.00,33222952000.00,17406123000.00,0.00,17406123000.00,0.00,15816829000.00,...,16978962000.00,6350183000.00,-1338715000.00,11967494000.00,10387972000.00,26204808000.00,756700.00,756700.00,111209000.00,111251000.00
17,2007,7203.T,167310507000.00,134336489000.00,32974018000.00,17333610000.00,0.00,17333610000.00,0.00,15640415000.00,...,16644950000.00,6275465000.00,-1116703000.00,11486188000.00,9659384000.00,25299792000.00,715400.00,714700.00,112364000.00,112427000.00
18,2006,7203.T,147549556000.00,118849227000.00,28700329000.00,15525895000.00,0.00,15525895000.00,0.00,13174434000.00,...,14640185000.00,5577096000.00,-561085000.00,9624174000.00,8495410000.00,21669844000.00,589050.00,588840.00,113869000.00,113911000.00
19,2005,7203.T,129670583000.00,103938989000.00,25731594000.00,14043540000.00,0.00,14043540000.00,0.00,11688061000.00,...,12264546000.00,4598363000.00,-520940000.00,8187123000.00,6974107000.00,18662161000.00,498750.00,498680.00,115360000.00,115388000.00
20,2004,7203.T,119418166000.00,95774189000.00,23643977000.00,12133968000.00,0.00,12133968000.00,0.00,11510009000.00,...,12192348000.00,4704126000.00,-535654000.00,8023876000.00,6697145000.00,18207154000.00,481040.00,481040.00,118615000.00,118629000.00
21,2003,7203.T,106500912000.00,84767179000.00,21733733000.00,12997467000.00,0.00,12997467000.00,0.00,8736273000.00,...,8710674000.00,3551821000.00,0.00,5158853000.00,5981360000.00,14717633000.00,294350.00,294350.00,124376000.00,124376000.00
22,2002,7203.T,99961589000.00,79132494000.00,20829088000.00,13193558000.00,0.00,13193558000.00,0.00,7635537000.00,...,6838209000.00,2952061000.00,0.00,3886148000.00,5654782000.00,13290312000.00,213780.00,213780.00,127939000.00,127939000.00
23,2001,7203.T,93599933000.00,75850992000.00,17748941000.00,12115110000.00,0.00,12115110000.00,0.00,5633831000.00,...,8540784000.00,3732344000.00,0.00,4808440000.00,5591453000.00,11225284000.00,254520.00,254520.00,130753000.00,130760000.00
24,2000,7203.T,86065763000.00,62475644000.00,23590112000.00,18856558000.00,0.00,13284320000.00,5572238000.00,4733561000.00,...,6129676000.00,2864162000.00,0.00,3265514000.00,5572238000.00,10305792000.00,174090.00,174090.00,131229000.00,131229000.00
25,1999,7203.T,88224843000.00,63662739000.00,24562104000.00,19372752000.00,0.00,13396453000.00,5976299000.00,5189352000.00,...,6068832000.00,2945215000.00,0.00,3123617000.00,5976299000.00,11165651000.00,165060.00,165060.00,132314000.00,132314000.00
26,1998,7203.T,82423852000.00,60180435000.00,22243417000.00,16994614000.00,0.00,12432609000.00,4562005000.00,5248803000.00,...,5708381000.00,2501709000.00,0.00,3206672000.00,4562005000.00,9810815000.00,167720.00,167720.00,127610000.00,127610000.00
27,1997,7203.T,85555309000.00,65101526000.00,20453783000.00,15807792000.00,0.00,11550154000.00,4257638000.00,4645984000.00,...,5171068000.00,2474451000.00,0.00,2696610000.00,4257638000.00,8903622000.00,140350.00,140350.00,134477000.00,134477000.00
28,1996,7203.T,75809881000.00,59872589000.00,15937285000.00,13475567000.00,0.00,9587921000.00,3887646000.00,2461718000.00,...,3115532000.00,1298031000.00,0.00,1817501000.00,3887646000.00,6349364000.00,92960.00,92960.00,136857000.00,136857000.00
29,1995,7203.T,57956346000.00,46719729000.00,11236617000.00,9411633000.00,0.00,7054250000.00,2357383000.00,1824977000.00,...,2074884000.00,1133209000.00,0.00,941675000.00,2357383000.00,4182367000.00,49000.00,49000.00,134554000.00,134554000.00
30,1994,7203.T,65484265000.00,53798255000.00,11686010000.00,10733219000.00,0.00,7515914000.00,3217305000.00,952791000.00,...,1746052000.00,866103000.00,0.00,879956000.00,3217305000.00,4170096000.00,46830.00,46830.00,131453000.00,131453000.00
31,1994,7203.T,71207584000.00,59013283000.00,12194301000.00,10925768000.00,0.00,7549717000.00,3376051000.00,1268533000.00,...,2356459000.00,1125796000.00,0.00,1230663000.00,3376051000.00,4644584000.00,64260.00,64260.00,134113000.00,134113000.00
32,1993,7203.T,71160635000.00,58110458000.00,13050184000.00,11520313000.00,0.00,8215410000.00,3304903000.00,1529871000.00,...,3153437000.00,1488130000.00,0.00,1665307000.00,3304903000.00,4834774000.00,86310.00,86310.00,135079000.00,135079000.00
33,1992,7203.T,69087648000.00,54986421000.00,14101220000.00,10597125000.00,0.00,7909846000.00,2687272000.00,3504102000.00,...,5134759000.00,2110143000.00,0.00,3024623000.00,2687272000.00,6191374000.00,156310.00,156310.00,135443000.00,135443000.00
34,1991,7203.T,64415491000.00,50028433000.00,14387058000.00,9881480000.00,0.00,7503188000.00,2378292000.00,4505578000.00,...,6001723000.00,2909501000.00,0.00,3092215000.00,2378292000.00,6883870000.00,175770.00,175770.00,123130000.00,123130000.00
35,1989,7203.T,56261282000.00,44960258000.00,11301024000.00,8018829000.00,0.00,5949328000.00,2069501000.00,3282195000.00,...,4515350000.00,2086630000.00,0.00,2428727000.00,2069501000.00,5351696000.00,140070.00,140070.00,121380000.00,121380000.00

In [22]:
cardata_a= tsla_clean.merge(toyota_clean, "outer")
cardata_a= cardata_a.merge(volkswagen_clean, "outer")
cardata_a= cardata_a.merge(ford_clean, "outer")
cardata_b= cardata_a.merge(gm_clean, "outer")
display(cardata_b)

Report Filing:,Year,company,Revenue,Cost of Revenue,Gross Profit,Operating Expenses,Research & Development,"Selling, General and Administrative",Other Operating Expenses,Operating Income,...,Income Before Tax,Income Tax Expense,Income Attributable to Non-Controlling Interest,Net Income,Depreciation and Amortization,EBITDA,Earnings Per Share (EPS),Diluted Earnings Per Share,Weighted Average Shares Outstanding,Diluted Weighted Average Shares Outstanding
0,1985,F,52774000000.00,44435000000.00,8339000000.00,5609000000.00,0.00,3217000000.00,2393000000.00,2730000000.00,...,3619000000.00,1103000000.00,0.00,2515000000.00,2393000000.00,5123000000.00,2290000.00,2220000.00,1098000000.00,1133000000.00
1,1986,F,62716000000.00,51866000000.00,10850000000.00,6793000000.00,0.00,3834000000.00,2960000000.00,4057000000.00,...,5059000000.00,1774000000.00,0.00,3285000000.00,2960000000.00,7016000000.00,3030000.00,3030000.00,1084000000.00,1084000000.00
2,1987,F,71643000000.00,58495000000.00,13148000000.00,6947000000.00,0.00,3780000000.00,3167000000.00,6201000000.00,...,7351000000.00,2726000000.00,0.00,4625000000.00,3167000000.00,9369000000.00,4520000.00,4450000.00,1023000000.00,1039000000.00
3,1988,F,92446000000.00,68233000000.00,24212000000.00,10765000000.00,0.00,8307000000.00,2458000000.00,13448000000.00,...,8299000000.00,2999000000.00,0.00,5300000000.00,2458000000.00,15905000000.00,5480000.00,5410000.00,967200000.00,979700000.00
4,1989,7203.T,56261282000.00,44960258000.00,11301024000.00,8018829000.00,0.00,5949328000.00,2069501000.00,3282195000.00,...,4515350000.00,2086630000.00,0.00,2428727000.00,2069501000.00,5351696000.00,140070.00,140070.00,121380000.00,121380000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2023,VOW3.DE,357735240000.00,290000820000.00,67734420000.00,42675060000.00,17564640000.00,37811040000.00,-12700620000.00,25059360000.00,...,25745340000.00,5845260000.00,1475190000.00,18424890000.00,29704710000.00,54764070000.00,35431200.00,35431200.00,556443000.00,556443000.00
128,2024,7203.T,315667275000.00,250089049000.00,65578226000.00,28107681000.00,8416611000.00,19691070000.00,0.00,37470545000.00,...,43413636000.00,13255655000.00,-4456550000.00,34614531000.00,14609462000.00,52080007000.00,2561300.00,2561300.00,94591000.00,94591000.00
129,2024,F,176191000000.00,160031000000.00,16160000000.00,10702000000.00,8200000000.00,10702000000.00,-8200000000.00,5458000000.00,...,3967000000.00,-362000000.00,-18000000.00,4347000000.00,6523000000.00,11981000000.00,1090000.00,1080000.00,3998000000.00,4041000000.00
130,2024,GM,171842000000.00,152704000000.00,19138000000.00,9840000000.00,9900000000.00,9840000000.00,-9900000000.00,9298000000.00,...,10403000000.00,563000000.00,-287000000.00,10127000000.00,11737000000.00,21035000000.00,7350000.00,7320000.00,1364000000.00,1369000000.00
131,2024,TSLA,96773000000.00,79113000000.00,17660000000.00,8769000000.00,3969000000.00,4800000000.00,0.00,8891000000.00,...,9973000000.00,-5001000000.00,-25000000.00,14999000000.00,4667000000.00,13558000000.00,4730000.00,4300000.00,3174000000.00,3485000000.00

In [25]:
cardata_b.to_csv("04-full_car_data_cleaned.csv",index=False)